/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttendanceChart: typeof import('./src/components/AttendanceChart.vue')['default']
    EmployeeForm: typeof import('./src/components/EmployeeForm.vue')['default']
    EmployeeList: typeof import('./src/components/EmployeeList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Holiday: typeof import('./src/components/Holiday.vue')['default']
    LeaveReqForm: typeof import('./src/components/mobile/LeaveReqForm.vue')['default']
    LeaveRequests: typeof import('./src/components/LeaveRequests.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Pay_entry: typeof import('./src/components/Pay_entry.vue')['default']
    Pay_period: typeof import('./src/components/Pay_period.vue')['default']
    Pph21Breakdown: typeof import('./src/components/pph21/Pph21Breakdown.vue')['default']
    Pph21Form: typeof import('./src/components/pph21/Pph21Form.vue')['default']
    Pph21Result: typeof import('./src/components/pph21/Pph21Result.vue')['default']
    Role_setup: typeof import('./src/components/Role_setup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Salary_component: typeof import('./src/components/Salary_component.vue')['default']
    Salary_structure: typeof import('./src/components/Salary_structure.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
